<a href="https://colab.research.google.com/github/mainackdasgupta/ML-Basics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

1. Introduction

In [ ]:
#intro
import numpy as np
import time
import sys
a = np.array([1,2,3])
print(a)
print(a[0])
print(a[2])

# who consumes less memory
l = range(1000)
print(sys.getsizeof(l)*len(l))
array = np.arange(1000)
print(array.size*array.itemsize)

# who is fast
size = 1000000
l1 = range(size)
l2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)
#python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took:",(time.time()-start)*1000) #1000 for miliseconds
# numpy array
start = time.time()
result = a1+a2
print("numpy took:", (time.time()-start)*1000)

#operations
a3 = np.array([4,5,6])
print(a+a3)
print(a*a3)

[1 2 3]
1
3
48000
8000
python list took: 134.66715812683105
numpy took: 18.17178726196289
[5 7 9]
[ 4 10 18]


2. Basic array operations

In [ ]:
import numpy as np
a1 = np.array([5,6,9])
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)
print(a1.ndim) #ndim is dimension
print(a.size)
print(a.itemsize)
print(a.dtype)

a = np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
print(a.itemsize)
print(a.dtype)
print(a.shape) # how many no. of rows and column
print(a)

a = np.array([[1,2],[3,4],[5,6]],dtype=np.complex)
print(a.itemsize)
print(a.dtype)
print(a)
print(a.reshape(2,3))
print(a.reshape(6,1))

print(np.arange(1,5))
print(np.arange(1,7))
print(np.arange(1,5,2))
print(np.linspace(1,5,10))
print(np.linspace(1,7,8))

print(a.min())
a3 = np.array([[1,3],[2,4],[5,6]])
b = np. array([[6,7],[8,9]])
print(a3.min())
print(a3.sum())
print(np.std(a3)) #std is standard deviation in numpy
print(np.sqrt(a3))
print(a3.sum(axis=0)) # axis 0 is for column
print(a3.sum(axis=1)) # axis 1 is for row
print(a3.dot(b))  #multiply the elements

2
1
6
8
int64
8
float64
(3, 2)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
16
complex128
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+0.j]
 [2.+0.j]
 [3.+0.j]
 [4.+0.j]
 [5.+0.j]
 [6.+0.j]]
[1 2 3 4]
[1 2 3 4 5 6]
[1 3]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1.         1.85714286 2.71428571 3.57142857 4.42857143 5.28571429
 6.14285714 7.        ]
(1+0j)
1
21
1.707825127659933
[[1.         1.73205081]
 [1.41421356 2.        ]
 [2.23606798 2.44948974]]
[ 8 13]
[ 4  6 11]
[[30 34]
 [44 50]
 [78 89]]


3. Slicing and stacking

In [ ]:
number1 = input("First number: ")
number2 = input("\nSecond number: ")
  
# Adding two numbers
# User might also enter float numbers
sum = float(number1) + float(number2)
  
# Display the sum
# will print value in float
print("The sum of {0} and {1} is {2}" .format(number1, number2, sum))


First number: 5

Second number: 2
The sum of 5 and 2 is 7.0


Sorted array is:
 11
 12
 22
 25
 34
 64
 90
